name: "Update flakes"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  update-flakes:
    if: ${{ hashFiles('flake.nix') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
      - uses: DeterminateSystems/update-flake-lock@v23
        with:
          # required to trigger GitHub Actions on the created PRs
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
